INSERT INTO product(id, product_name, category_id,uom_id, details) VALUES 
(103,'Boom Flower', (select id from product_category where category_name ilike 'Foliar'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'http://www.highchem.co.ke/product_details.php?lang=en&token=1481008460&pidentity=highchemgroup2027&category=Crop%20Science' ),
(104,'Twiga Ace', (select id from product_category where category_name ilike 'Fungicide'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'http://www.twigachemicals.com/products/twiga-ace-20sl/' ),
(105,'Profile® 440EC', (select id from product_category where category_name ilike 'Pesticide'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'https://www.greenlife.co.ke/profile-440ec/' ),
(106,'Thunder', (select id from product_category where category_name ilike 'Pesticide'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'' ),
(107,'Confidor', (select id from product_category where category_name ilike 'Pesticide'), (select id from unit_of_measure where uom_name ilike 'gram%'),
'' ),
(108,'Otiver Top', (select id from product_category where category_name ilike 'Fungicide'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'https://www.syngenta.co.ke/product/crop-protection/fungicides/ortiva-top' ),
(109,'Multi-NPK. 13:2:44', (select id from product_category where category_name ilike 'Foliar'), (select id from unit_of_measure where uom_name ilike 'gram%'),
'https://web.facebook.com/AmiranKenya/posts/multi-npk-13:2:44-potassium-improves/1070739462936320/?_rdc=1&_rdr' ),
(110,'Easy Grow', (select id from product_category where category_name ilike 'Foliar'), (select id from unit_of_measure where uom_name ilike 'gram%'),
'http://www.oshochem.com/cropprotection.html' ),
(111,'Desis', (select id from product_category where category_name ilike 'Fungicide'), (select id from unit_of_measure where uom_name ilike 'gram%'),
'Amiran tentativly' ),
(112,'Caprocafaro', (select id from product_category where category_name ilike 'Fungicide'), (select id from unit_of_measure where uom_name ilike 'gram%'),
'Amiran tentativly' ),
(113,'DUDUTHRIN 1.75EC', (select id from product_category where category_name ilike 'Fungicide'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'http://www.twigachemicals.com/products/duduthrin-1-75ec/' ),
(114,'DAP', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'http://www.mea.co.ke/Complex' ),
(115,'CAN', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'http://www.mea.co.ke/Complex' ),
(116,'NPK-17', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'http://www.mea.co.ke/Complex' ),
(117,'NPK-23', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'http://www.mea.co.ke/Complex' ),
(118,'Manure-Cattle', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'' ),
(119,'Manure-Goat', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'' ),
(120,'Manure-Compost', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'' ),
(121,'Manure-Chicken', (select id from product_category where category_name ilike 'Fertilizer'), (select id from unit_of_measure where uom_name ilike '%Kilogram%'),
'' ),
(122,'SuperGrow', (select id from product_category where category_name ilike 'Foliar'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'https://www.neolife.com/en-ke/product/HomeCare/SuperGro' ),
(123,'Ridomill', (select id from product_category where category_name ilike 'Fungicide'), (select id from unit_of_measure where uom_name ilike '%mili%'),
'http://www.syngenta-us.com/fungicides/ridomil-gold-sl' )
;


